### ISSUE TITLE
Does `Storing AWS Device Farm results in directory` feature still work well?

### ISSUE THREAD

**Issue by ainoya** [awslabs/aws-device-farm-jenkins-plugin#22]
Hi, this great plugin almost works well, but `Storing AWS Device Farm result` feature always fails in my environment, as causing `Status Code: 500; Error Code: InternalFailure`.  Does anyone have same issue ?

device-farm plugin version: 1.9
Jenkins version: 1.580.2

Error messages below;

```
[AWSDeviceFarm] Test run is complete.
[AWSDeviceFarm] Storing AWS Device Farm results in directory /var/jenkins_home/jobs/***mask***/builds/30/archive/AWS Device Farm Results
ERROR: Build step failed with exception
com.amazonaws.AmazonServiceException: null (Service: AWSDeviceFarm; Status Code: 500; Error Code: InternalFailure; Request ID: f1d5a8bb-5ae5-11e5-bfaf-7549af5d7ebf)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
	at com.amazonaws.services.devicefarm.AWSDeviceFarmClient.invoke(AWSDeviceFarmClient.java:1524)
	at com.amazonaws.services.devicefarm.AWSDeviceFarmClient.listSuites(AWSDeviceFarmClient.java:1263)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarm.listSuites(AWSDeviceFarm.java:488)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.getSuites(AWSDeviceFarmRecorder.java:373)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:311)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'Run Tests on AWS Device Farm' marked build as failure
```

**Comment by trentpeterson** [comment]
We're looking into this issue and will let you know if we have further questions or have a workaround/fix. Thanks for reporting it.

**Comment by anurag1408** [comment]
We have identified the issue and the fix will be released in the Device Farm plugin build we are releasing next week
