### ISSUE TITLE
Store test results locally option NOT working

### ISSUE THREAD

**Issue by whoismikem** [awslabs/aws-device-farm-jenkins-plugin#40]
Plugin works fine unless the 'Store test results locally' option is selected. The job fails with the below error message. Looks like there was an issue submitted around this feature in the recent past. 

Is this feature still working?

Jenkins 2.19
aws-device-farm Plugin version: 1.13

Console Output Snippet: 
```
[AWSDeviceFarm] Test run is complete.
[AWSDeviceFarm] Storing AWS Device Farm results in directory C:\Jenkins\jobs\Calc3-Android-UI_Tests\builds\6\archive\AWS Device Farm Results
ERROR: Build step failed with exception
java.lang.NullPointerException
	at hudson.FilePath.isAbsolute(FilePath.java:281)
	at hudson.FilePath.resolvePathIfRelative(FilePath.java:266)
	at hudson.FilePath.<init>(FilePath.java:262)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.getSuites(AWSDeviceFarmRecorder.java:427)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:356)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Run Tests on AWS Device Farm' marked build as failure
Finished: FAILURE
```

**Comment by nikhil-dabhade** [comment]
@whoismikem : Thanks for highlighting this. We will need to test this out at our end. We have other users who use this feature and this is the first and only instance of this issue being reported.

**Comment by whoismikem** [comment]
If you think the feature is working and problem is on my end, I can troubleshoot this a little more if you point me in the right direction.

Thanks

**Comment by nikhil-dabhade** [comment]
Sorry for the delay here @whoismikem 
Are you still seeing this issue?

**Comment by whoismikem** [comment]
Yes. Still seeing this problem. @nikhil-dabhade. Not sure how to approach troubleshooting this.

**Comment by anurag1408** [comment]
Here is the source code for the Device Farm Jenkins plugin
https://github.com/jenkinsci/aws-device-farm-plugin

You can clone this repo and run
mvn compile hpi:hpi
This will generate a hpi file in the target directory under your workspace. You can use this hpi file for the device farm plugin in the Jenkins

Meanwhile this is the file , where you are getting the NPE. 
Can you add more logging to see what exactly is giving the NPE.
https://github.com/jenkinsci/aws-device-farm-plugin/blob/master/src/main/java/org/jenkinsci/plugins/awsdevicefarm/AWSDeviceFarmRecorder.java#L427
