### ISSUE TITLE
NPE with 1.19

### ISSUE THREAD

**Issue by arthur-c** [awslabs/aws-device-farm-jenkins-plugin#78]
Hi,

I have the following error with the 1.19 version (I rollbacked to 1.17 and it's fine)
I'm using an unmetered device.

```
[Pipeline] devicefarm
[AWSDeviceFarm] Using Project 'xxx'
[AWSDeviceFarm] Using DevicePool 'devicepool-android-prod'
[AWSDeviceFarm] Using App 'app-test.apk'
[AWSDeviceFarm] Archiving artifact 'app-test.apk'
[AWSDeviceFarm] Uploading app-test.apk to S3
[AWSDeviceFarm] Waiting for upload app-test.apk to be ready (current status: INITIALIZED)
[AWSDeviceFarm] Upload app-test.apk succeeded
[AWSDeviceFarm] Getting test to schedule.
[AWSDeviceFarm] Archiving artifact 'app-test-autotest-build-27-v1.6.apk'
[AWSDeviceFarm] Uploading app-test-autotest-build-27-v1.6.apk to S3
[AWSDeviceFarm] Waiting for upload app-test-autotest-build-27-v1.6.apk to be ready (current status: PROCESSING)
[AWSDeviceFarm] Upload app-test-autotest-build-27-v1.6.apk succeeded
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

java.lang.NullPointerException
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.getScheduleRunTest(AWSDeviceFarmRecorder.java:1011)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:557)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by nikhil-dabhade** [comment]
@arthur-c : Thank you for bringing this to our attention.  We are taking a look at this immediately. I will update this thread with the results.

**Comment by nikhil-dabhade** [comment]
@arthur-c  We have identified the root cause for this issue and are working on the fix. Will update you as soon as this makes it in. (shooting for 08/30 as a best effort estimate)

**Comment by arthur-c** [comment]
Hi @nikhil-dabhade 

I updated the plugin and retried, I have got a new NPE:

```java.lang.NullPointerException
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:592)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE```

A rollback to 1.17 fix the issue.
