### ISSUE TITLE
NPE 1.20

### ISSUE THREAD

**Issue by ravuthlong** [awslabs/aws-device-farm-jenkins-plugin#81]
Issue on 1.20

ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:592)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1823)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Refer to https://github.com/awslabs/aws-device-farm-jenkins-plugin/issues/78

**Comment by ravuthlong** [comment]
Resolve after i change Appium version from 1.65 to 1.72 in jenkins Job it works fine.
